/*
 * 自动生成的 C 头文件
 * 由 cbindgen 从 Rust FFI 代码生成
 * 请勿手动编辑此文件
 */


#ifndef IM_PARSE_CORE_H
#define IM_PARSE_CORE_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * FFI 错误类型
 */
typedef struct FFIError {
  int32_t code;
  const char *message;
} FFIError;

/**
 * 解析结果
 */
typedef struct ParseResult {
  bool success;
  const char *ast_json;
  struct FFIError error;
} ParseResult;

/**
 * 释放 CString
 */
void free_string(char *ptr);

/**
 * 解析 Markdown 为 JSON AST
 */
struct ParseResult *parse_markdown_to_json(const char *input);

/**
 * 解析 Delta 为 JSON AST
 */
struct ParseResult *parse_delta_to_json(const char *input);

/**
 * 释放 ParseResult
 */
void free_parse_result(struct ParseResult *result);

/**
 * 将 Markdown 转换为 HTML
 */
struct ParseResult *markdown_to_html(const char *input);

/**
 * 将 Markdown 转换为 HTML（使用样式配置）
 * @param input Markdown 字符串
 * @param config_json 样式配置 JSON 字符串，如果为 null 则使用默认配置
 */
struct ParseResult *markdown_to_html_with_config(const char *input, const char *config_json);

/**
 * 将 Delta 转换为 HTML
 */
struct ParseResult *delta_to_html(const char *input);

/**
 * 将 Delta 转换为 HTML（使用样式配置）
 * @param input Delta JSON 字符串
 * @param config_json 样式配置 JSON 字符串，如果为 null 则使用默认配置
 */
struct ParseResult *delta_to_html_with_config(const char *input, const char *config_json);

/**
 * 获取默认样式配置 JSON
 */
char *get_default_style_config(void);

/**
 * 获取深色模式样式配置 JSON
 */
char *get_dark_style_config(void);

/**
 * 将数学公式转换为 HTML
 * @param formula 数学公式字符串（LaTeX 格式）
 * @param display 是否为块级公式（true 为块级，false 为行内）
 */
struct ParseResult *math_to_html(const char *formula, bool display);

/**
 * 将 Mermaid 图表转换为 HTML
 * @param mermaid_code Mermaid 语法代码
 * @param text_color 文本颜色（十六进制，如 "#000000"）
 * @param background_color 背景颜色（十六进制，如 "#ffffff"）
 */
struct ParseResult *mermaid_to_html(const char *mermaid_code,
                                    const char *text_color,
                                    const char *background_color);

#endif  /* IM_PARSE_CORE_H */
